name: Bug Report
description: Einen Fehler im Code melden
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Danke, dass Sie einen Fehler melden! Bitte füllen Sie die folgenden Felder aus.
  
  - type: textarea
    id: description
    attributes:
      label: Beschreibung des Problems
      description: Was funktioniert nicht wie erwartet?
      placeholder: Beschreiben Sie das Problem so detailliert wie möglich
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Schritte zur Reproduktion
      description: Wie können wir das Problem nachstellen?
      placeholder: |
        1. Kompiliere das Projekt mit '...'
        2. Führe aus '...'
        3. Wähle Menüpunkt '...'
        4. Fehler tritt auf
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      description: Was sollte stattdessen passieren?
    validations:
      required: true
  
  - type: input
    id: os
    attributes:
      label: Betriebssystem
      placeholder: z.B. Windows 11, Ubuntu 22.04, macOS 14
    validations:
      required: true
  
  - type: input
    id: compiler
    attributes:
      label: Compiler
      placeholder: z.B. GCC 11.2, MSVC 2022, Clang 14
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Zusätzliche Informationen
      description: Screenshots, Fehlermeldungen, etc.
