//
// Created by Marvin Temmen on 12.05.20.
//

#ifndef CUEBUNGSAUFGABEN_FUNKTIONENAUFGABE2_H
#define CUEBUNGSAUFGABEN_FUNKTIONENAUFGABE2_H
void c_menue();
#endif //CUEBUNGSAUFGABEN_FUNKTIONENAUFGABE2_H
