//
// Created by Marvin Temmen on 12.05.20.
//

#ifndef CUEBUNGSAUFGABEN_SCHLEIFENUNDALTERNATIVEN_H
#define CUEBUNGSAUFGABEN_SCHLEIFENUNDALTERNATIVEN_H
void schleifenUndAlternativenMenue();
#endif //CUEBUNGSAUFGABEN_SCHLEIFENUNDALTERNATIVEN_H
